# Basic
title: 喜欢白醋
subtitle:
welcome_message: <a href="https://shencunzailaozhang.github.io/#blog" target="_blank">fighting!</a>
description: 即便是这样的我，心中也有誓死想要守护的人啊
creator: <a href="https://shencunzailaozhang.github.io/#blog">@shencunzailaozhang</a>

url: "https://shencunzailaozhang.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/shencunzailaozhang'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
#    disqus: vno-jekyll
#     duoshuo:
    
# Social
social:
#    weibo: onevcat
    github: shencunzailaozhang
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: 1137804516@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
