# Basic
title: 肤浅的大西瓜
subtitle: 
welcome_message: <a href="http:www.loulijun.com" target="_blank">欢迎来互相伤害</a>
description: iOS码农
creator: <a href="http://www.loulijun.com">@loulijun</a>

url: "http://www.loulijun.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: loulijun
    github: loulijun
    twitter: loulijun

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
